[2025-08-09T19:31:48.849+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-09T19:31:48.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xrs_update_12h.backfill_ncei_yesterday manual__2025-08-09T19:31:30.463747+00:00 [queued]>
[2025-08-09T19:31:48.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xrs_update_12h.backfill_ncei_yesterday manual__2025-08-09T19:31:30.463747+00:00 [queued]>
[2025-08-09T19:31:48.906+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-09T19:31:48.922+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backfill_ncei_yesterday> on 2025-08-09 19:31:30.463747+00:00
[2025-08-09T19:31:48.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xrs_update_12h', 'backfill_ncei_yesterday', 'manual__2025-08-09T19:31:30.463747+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/xrs_update_daily.py', '--cfg-path', '/tmp/tmpqd95g7vm']
[2025-08-09T19:31:48.937+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask backfill_ncei_yesterday
[2025-08-09T19:31:48.937+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=274) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-09T19:31:48.938+0000] {standard_task_runner.py:63} INFO - Started process 275 to run task
[2025-08-09T19:31:49.002+0000] {task_command.py:426} INFO - Running <TaskInstance: xrs_update_12h.backfill_ncei_yesterday manual__2025-08-09T19:31:30.463747+00:00 [running]> on host 9d4e07229e62
[2025-08-09T19:31:49.059+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'backfill_ncei_yesterday', field 'bash_command'. Template: 'python /opt/project/src/data/xrs_update.py --mode backfill --start {{ (ds | ds_add(-1)) }} --end {{ (ds | ds_add(-1)) }}'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.from_string(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1108, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'ds_add'.
[2025-08-09T19:31:49.061+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.from_string(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1108, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'ds_add'.
[2025-08-09T19:31:49.073+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=xrs_update_12h, task_id=backfill_ncei_yesterday, run_id=manual__2025-08-09T19:31:30.463747+00:00, execution_date=20250809T193130, start_date=20250809T193148, end_date=20250809T193149
[2025-08-09T19:31:49.092+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task backfill_ncei_yesterday (No filter named 'ds_add'.; 275)
[2025-08-09T19:31:49.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-09T19:31:49.136+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-09T19:31:49.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
