[2025-08-12T11:22:11.086+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T11:22:11.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.ensure_kernel scheduled__2025-08-11T12:00:00+00:00 [queued]>
[2025-08-12T11:22:11.121+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.ensure_kernel scheduled__2025-08-11T12:00:00+00:00 [queued]>
[2025-08-12T11:22:11.122+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 5
[2025-08-12T11:22:11.132+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): ensure_kernel> on 2025-08-11 12:00:00+00:00
[2025-08-12T11:22:11.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'ensure_kernel', 'scheduled__2025-08-11T12:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmpjlxg8qyc']
[2025-08-12T11:22:11.142+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1104) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T11:22:11.143+0000] {standard_task_runner.py:91} INFO - Job 109: Subtask ensure_kernel
[2025-08-12T11:22:11.143+0000] {standard_task_runner.py:63} INFO - Started process 1105 to run task
[2025-08-12T11:22:11.193+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.ensure_kernel scheduled__2025-08-11T12:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T11:22:11.279+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='ensure_kernel' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-11T12:00:00+00:00'
[2025-08-12T11:22:11.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T11:22:11.290+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T11:22:11.292+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -e\n# 1) make sure ipykernel is present\npython -c "import ipykernel" 2>/dev/null || pip install --no-cache-dir ipykernel==6.29.5\n# 2) (re)install a kernelspec named \'***\'\npython -m ipykernel install --user --name *** --display-name \'Python 3 (Airflow)\'\n# 3) FIX kernel.json so argv[0] is a real python path (not empty)\nKDIR="$HOME/.local/share/jupyter/kernels/***"\nPYBIN="$(command -v python)"\ncat > "$KDIR/kernel.json" <<JSON\n{\n "argv": ["$PYBIN", "-Xfrozen_modules=off", "-m", "ipykernel_launcher", "-f", "{connection_file}"],\n "display_name": "Python 3 (Airflow)",\n "language": "python"\n}\nJSON\necho "Kernel fixed at $KDIR/kernel.json with PYBIN=$PYBIN"']
[2025-08-12T11:22:11.302+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T11:22:12.511+0000] {subprocess.py:93} INFO - Installed kernelspec *** in /home/***/.local/share/jupyter/kernels/***
[2025-08-12T11:22:12.602+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 10: /.local/share/jupyter/kernels/***/kernel.json: No such file or directory
[2025-08-12T11:22:12.602+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T11:22:12.603+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T11:22:12.614+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T11:22:12.617+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=ensure_kernel, run_id=scheduled__2025-08-11T12:00:00+00:00, execution_date=20250811T120000, start_date=20250812T112211, end_date=20250812T112212
[2025-08-12T11:22:12.628+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 109 for task ensure_kernel (Bash command failed. The command returned a non-zero exit code 1.; 1105)
[2025-08-12T11:22:12.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T11:22:12.659+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T11:22:12.662+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
