[2025-08-12T13:48:21.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T13:48:21.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T13:48:21.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T13:48:21.862+0000] {taskinstance.py:2306} INFO - Starting attempt 11 of 13
[2025-08-12T13:48:21.880+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_notebook> on 2025-08-12 00:00:00+00:00
[2025-08-12T13:48:21.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'train_notebook', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmpejg5oe3e']
[2025-08-12T13:48:21.896+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask train_notebook
[2025-08-12T13:48:21.901+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5447) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T13:48:21.902+0000] {standard_task_runner.py:63} INFO - Started process 5448 to run task
[2025-08-12T13:48:21.972+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T13:48:22.099+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='train_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T13:48:22.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T13:48:22.119+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T13:48:22.130+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -e\nmkdir -p /opt/project/notebooks/runs\ncd /opt/project/notebooks\nOUT="ml_x_ray_sensor_run_20250812T000000.ipynb"\npython -m papermill -k *** ml_x_ray_sensor.ipynb "$OUT"\necho "Notebook exécuté -> $OUT"']
[2025-08-12T13:48:22.147+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T13:48:24.088+0000] {subprocess.py:93} INFO - Input Notebook:  ml_x_ray_sensor.ipynb
[2025-08-12T13:48:24.089+0000] {subprocess.py:93} INFO - Output Notebook: ml_x_ray_sensor_run_20250812T000000.ipynb
[2025-08-12T13:48:27.919+0000] {subprocess.py:93} INFO - Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: ***
[2025-08-12T13:49:27.776+0000] {subprocess.py:93} INFO - Executing:   5%|▌         | 1/20 [00:07<02:29,  7.85s/cell]Executing:  10%|█         | 2/20 [00:07<00:59,  3.30s/cell]Executing:  20%|██        | 4/20 [00:08<00:20,  1.27s/cell]Executing:  25%|██▌       | 5/20 [00:09<00:17,  1.19s/cell]Executing:  35%|███▌      | 7/20 [00:09<00:09,  1.38cell/s]Executing:  40%|████      | 8/20 [00:09<00:07,  1.58cell/s]Executing:  45%|████▌     | 9/20 [00:09<00:05,  2.02cell/s]Executing:  55%|█████▌    | 11/20 [00:10<00:03,  2.71cell/s]Executing:  65%|██████▌   | 13/20 [00:10<00:01,  3.96cell/s]Executing:  70%|███████   | 14/20 [01:01<01:06, 11.17s/cell]Executing:  75%|███████▌  | 15/20 [01:01<00:42,  8.58s/cell]Executing:  85%|████████▌ | 17/20 [01:02<00:15,  5.17s/cell]Executing:  90%|█████████ | 18/20 [01:03<00:07,  3.53s/cell]
[2025-08-12T13:49:27.792+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T13:49:27.792+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-08-12T13:49:27.792+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 88, in _run_code
[2025-08-12T13:49:27.793+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/__main__.py", line 4, in <module>
[2025-08-12T13:49:27.793+0000] {subprocess.py:93} INFO -     papermill()
[2025-08-12T13:49:27.794+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
[2025-08-12T13:49:27.794+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-08-12T13:49:27.794+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:49:27.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
[2025-08-12T13:49:27.795+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-08-12T13:49:27.795+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-08-12T13:49:27.796+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
[2025-08-12T13:49:27.796+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-08-12T13:49:27.797+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:49:27.797+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
[2025-08-12T13:49:27.797+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-08-12T13:49:27.798+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:49:27.798+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
[2025-08-12T13:49:27.798+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-08-12T13:49:27.799+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:49:27.799+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
[2025-08-12T13:49:27.799+0000] {subprocess.py:93} INFO -     execute_notebook(
[2025-08-12T13:49:27.800+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-08-12T13:49:27.800+0000] {subprocess.py:93} INFO -     raise_for_execution_errors(nb, output_path)
[2025-08-12T13:49:27.800+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-08-12T13:49:27.801+0000] {subprocess.py:93} INFO -     raise error
[2025-08-12T13:49:27.801+0000] {subprocess.py:93} INFO - papermill.exceptions.PapermillExecutionError:
[2025-08-12T13:49:27.801+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T13:49:27.801+0000] {subprocess.py:93} INFO - Exception encountered at "In [16]":
[2025-08-12T13:49:27.802+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T13:49:27.802+0000] {subprocess.py:93} INFO - ImportError                               Traceback (most recent call last)
[2025-08-12T13:49:27.803+0000] {subprocess.py:93} INFO - Cell In[16], line 20
[2025-08-12T13:49:27.803+0000] {subprocess.py:93} INFO -      18 # Evidently 0.7+
[2025-08-12T13:49:27.803+0000] {subprocess.py:93} INFO -      19 from evidently import Report
[2025-08-12T13:49:27.804+0000] {subprocess.py:93} INFO - ---> 20 from evidently.metrics import ClassificationPreset
[2025-08-12T13:49:27.804+0000] {subprocess.py:93} INFO -      21 from evidently.metrics.data_drift.data_definition import (
[2025-08-12T13:49:27.804+0000] {subprocess.py:93} INFO -      22     DataDefinition, MulticlassClassification
[2025-08-12T13:49:27.804+0000] {subprocess.py:93} INFO -      23 )
[2025-08-12T13:49:27.805+0000] {subprocess.py:93} INFO -      25 # MLflow tracking (ne pas toucher au docker)
[2025-08-12T13:49:27.805+0000] {subprocess.py:93} INFO - 
[2025-08-12T13:49:27.806+0000] {subprocess.py:93} INFO - ImportError: cannot import name 'ClassificationPreset' from 'evidently.metrics' (/home/***/.local/lib/python3.12/site-packages/evidently/metrics/__init__.py)
[2025-08-12T13:49:27.806+0000] {subprocess.py:93} INFO - 
[2025-08-12T13:49:27.972+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T13:49:27.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T13:49:27.990+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T13:49:27.995+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=train_notebook, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T134821, end_date=20250812T134927
[2025-08-12T13:49:28.009+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 137 for task train_notebook (Bash command failed. The command returned a non-zero exit code 1.; 5448)
[2025-08-12T13:49:28.055+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T13:49:28.071+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T13:49:28.075+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
