[2025-08-12T12:41:35.619+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T12:41:35.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T12:41:35.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T12:41:35.666+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-12T12:41:35.680+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_notebook> on 2025-08-12 00:00:00+00:00
[2025-08-12T12:41:35.690+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'train_notebook', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmpjsgkhgl7']
[2025-08-12T12:41:35.692+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T12:41:35.692+0000] {standard_task_runner.py:91} INFO - Job 127: Subtask train_notebook
[2025-08-12T12:41:35.693+0000] {standard_task_runner.py:63} INFO - Started process 3265 to run task
[2025-08-12T12:41:36.465+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T12:41:36.541+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='train_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T12:41:36.543+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T12:41:37.656+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T12:41:37.657+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -e\nmkdir -p /opt/project/notebooks/runs\ncd /opt/project/notebooks\nOUT="ml_x_ray_sensor_run_20250812T000000.ipynb"\npython -m papermill -k *** ml_x_ray_sensor.ipynb "$OUT"\necho "Notebook exécuté -> $OUT"']
[2025-08-12T12:41:37.669+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T12:41:39.076+0000] {subprocess.py:93} INFO - Input Notebook:  ml_x_ray_sensor.ipynb
[2025-08-12T12:41:39.077+0000] {subprocess.py:93} INFO - Output Notebook: ml_x_ray_sensor_run_20250812T000000.ipynb
[2025-08-12T12:41:40.658+0000] {subprocess.py:93} INFO - Executing:   0%|          | 0/22 [00:00<?, ?cell/s]Executing notebook with kernel: ***
[2025-08-12T12:41:46.414+0000] {subprocess.py:93} INFO - Executing:   5%|▍         | 1/22 [00:01<00:32,  1.54s/cell]Executing:   9%|▉         | 2/22 [00:05<01:03,  3.18s/cell]Executing:  14%|█▎        | 3/22 [00:06<00:36,  1.91s/cell]Executing:  14%|█▎        | 3/22 [00:07<00:46,  2.43s/cell]
[2025-08-12T12:41:46.425+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T12:41:46.425+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-08-12T12:41:46.426+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 88, in _run_code
[2025-08-12T12:41:46.426+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/__main__.py", line 4, in <module>
[2025-08-12T12:41:46.426+0000] {subprocess.py:93} INFO -     papermill()
[2025-08-12T12:41:46.427+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
[2025-08-12T12:41:46.427+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-08-12T12:41:46.427+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T12:41:46.428+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
[2025-08-12T12:41:46.428+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-08-12T12:41:46.428+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-08-12T12:41:46.428+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
[2025-08-12T12:41:46.428+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-08-12T12:41:46.429+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T12:41:46.429+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
[2025-08-12T12:41:46.429+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-08-12T12:41:46.429+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T12:41:46.430+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
[2025-08-12T12:41:46.430+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-08-12T12:41:46.430+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T12:41:46.430+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
[2025-08-12T12:41:46.430+0000] {subprocess.py:93} INFO -     execute_notebook(
[2025-08-12T12:41:46.431+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-08-12T12:41:46.431+0000] {subprocess.py:93} INFO -     raise_for_execution_errors(nb, output_path)
[2025-08-12T12:41:46.431+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-08-12T12:41:46.431+0000] {subprocess.py:93} INFO -     raise error
[2025-08-12T12:41:46.432+0000] {subprocess.py:93} INFO - papermill.exceptions.PapermillExecutionError:
[2025-08-12T12:41:46.432+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T12:41:46.432+0000] {subprocess.py:93} INFO - Exception encountered at "In [2]":
[2025-08-12T12:41:46.432+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T12:41:46.432+0000] {subprocess.py:93} INFO - FileNotFoundError                         Traceback (most recent call last)
[2025-08-12T12:41:46.433+0000] {subprocess.py:93} INFO - Cell In[2], line 5
[2025-08-12T12:41:46.433+0000] {subprocess.py:93} INFO -       3 parquet_path = Path(r"C:\Users\gate\Documents\Jedha\Projet\4\mlops-solar-flares\data\xrs_clean.parquet")
[2025-08-12T12:41:46.433+0000] {subprocess.py:93} INFO -       4 df = parquet_path
[2025-08-12T12:41:46.433+0000] {subprocess.py:93} INFO - ----> 5 df = pd.read_parquet(parquet_path, engine="pyarrow")
[2025-08-12T12:41:46.433+0000] {subprocess.py:93} INFO -       6 print(f"✅ Données chargées : {df.shape[0]} lignes, {df.shape[1]} colonnes")
[2025-08-12T12:41:46.434+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:41:46.434+0000] {subprocess.py:93} INFO - File ~/.local/lib/python3.12/site-packages/pandas/io/parquet.py:670, in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, dtype_backend, filesystem, filters, **kwargs)
[2025-08-12T12:41:46.434+0000] {subprocess.py:93} INFO -     667     use_nullable_dtypes = False
[2025-08-12T12:41:46.434+0000] {subprocess.py:93} INFO -     668 check_dtype_backend(dtype_backend)
[2025-08-12T12:41:46.434+0000] {subprocess.py:93} INFO - --> 670 return impl.read(
[2025-08-12T12:41:46.435+0000] {subprocess.py:93} INFO -     671     path,
[2025-08-12T12:41:46.435+0000] {subprocess.py:93} INFO -     672     columns=columns,
[2025-08-12T12:41:46.435+0000] {subprocess.py:93} INFO -     673     filters=filters,
[2025-08-12T12:41:46.435+0000] {subprocess.py:93} INFO -     674     storage_options=storage_options,
[2025-08-12T12:41:46.435+0000] {subprocess.py:93} INFO -     675     use_nullable_dtypes=use_nullable_dtypes,
[2025-08-12T12:41:46.436+0000] {subprocess.py:93} INFO -     676     dtype_backend=dtype_backend,
[2025-08-12T12:41:46.436+0000] {subprocess.py:93} INFO -     677     filesystem=filesystem,
[2025-08-12T12:41:46.436+0000] {subprocess.py:93} INFO -     678     **kwargs,
[2025-08-12T12:41:46.436+0000] {subprocess.py:93} INFO -     679 )
[2025-08-12T12:41:46.437+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:41:46.437+0000] {subprocess.py:93} INFO - File ~/.local/lib/python3.12/site-packages/pandas/io/parquet.py:265, in PyArrowImpl.read(self, path, columns, filters, use_nullable_dtypes, dtype_backend, storage_options, filesystem, **kwargs)
[2025-08-12T12:41:46.437+0000] {subprocess.py:93} INFO -     262 if manager == "array":
[2025-08-12T12:41:46.437+0000] {subprocess.py:93} INFO -     263     to_pandas_kwargs["split_blocks"] = True  # type: ignore[assignment]
[2025-08-12T12:41:46.437+0000] {subprocess.py:93} INFO - --> 265 path_or_handle, handles, filesystem = _get_path_or_handle(
[2025-08-12T12:41:46.437+0000] {subprocess.py:93} INFO -     266     path,
[2025-08-12T12:41:46.438+0000] {subprocess.py:93} INFO -     267     filesystem,
[2025-08-12T12:41:46.438+0000] {subprocess.py:93} INFO -     268     storage_options=storage_options,
[2025-08-12T12:41:46.438+0000] {subprocess.py:93} INFO -     269     mode="rb",
[2025-08-12T12:41:46.438+0000] {subprocess.py:93} INFO -     270 )
[2025-08-12T12:41:46.438+0000] {subprocess.py:93} INFO -     271 try:
[2025-08-12T12:41:46.439+0000] {subprocess.py:93} INFO -     272     pa_table = self.api.parquet.read_table(
[2025-08-12T12:41:46.439+0000] {subprocess.py:93} INFO -     273         path_or_handle,
[2025-08-12T12:41:46.439+0000] {subprocess.py:93} INFO -     274         columns=columns,
[2025-08-12T12:41:46.439+0000] {subprocess.py:93} INFO -    (...)    277         **kwargs,
[2025-08-12T12:41:46.439+0000] {subprocess.py:93} INFO -     278     )
[2025-08-12T12:41:46.440+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:41:46.440+0000] {subprocess.py:93} INFO - File ~/.local/lib/python3.12/site-packages/pandas/io/parquet.py:139, in _get_path_or_handle(path, fs, storage_options, mode, is_dir)
[2025-08-12T12:41:46.440+0000] {subprocess.py:93} INFO -     129 handles = None
[2025-08-12T12:41:46.440+0000] {subprocess.py:93} INFO -     130 if (
[2025-08-12T12:41:46.440+0000] {subprocess.py:93} INFO -     131     not fs
[2025-08-12T12:41:46.440+0000] {subprocess.py:93} INFO -     132     and not is_dir
[2025-08-12T12:41:46.441+0000] {subprocess.py:93} INFO -    (...)    137     # fsspec resources can also point to directories
[2025-08-12T12:41:46.441+0000] {subprocess.py:93} INFO -     138     # this branch is used for example when reading from non-fsspec URLs
[2025-08-12T12:41:46.441+0000] {subprocess.py:93} INFO - --> 139     handles = get_handle(
[2025-08-12T12:41:46.441+0000] {subprocess.py:93} INFO -     140         path_or_handle, mode, is_text=False, storage_options=storage_options
[2025-08-12T12:41:46.442+0000] {subprocess.py:93} INFO -     141     )
[2025-08-12T12:41:46.442+0000] {subprocess.py:93} INFO -     142     fs = None
[2025-08-12T12:41:46.442+0000] {subprocess.py:93} INFO -     143     path_or_handle = handles.handle
[2025-08-12T12:41:46.442+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:41:46.442+0000] {subprocess.py:93} INFO - File ~/.local/lib/python3.12/site-packages/pandas/io/common.py:872, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
[2025-08-12T12:41:46.442+0000] {subprocess.py:93} INFO -     863         handle = open(
[2025-08-12T12:41:46.443+0000] {subprocess.py:93} INFO -     864             handle,
[2025-08-12T12:41:46.443+0000] {subprocess.py:93} INFO -     865             ioargs.mode,
[2025-08-12T12:41:46.443+0000] {subprocess.py:93} INFO -    (...)    868             newline="",
[2025-08-12T12:41:46.443+0000] {subprocess.py:93} INFO -     869         )
[2025-08-12T12:41:46.444+0000] {subprocess.py:93} INFO -     870     else:
[2025-08-12T12:41:46.444+0000] {subprocess.py:93} INFO -     871         # Binary mode
[2025-08-12T12:41:46.444+0000] {subprocess.py:93} INFO - --> 872         handle = open(handle, ioargs.mode)
[2025-08-12T12:41:46.445+0000] {subprocess.py:93} INFO -     873     handles.append(handle)
[2025-08-12T12:41:46.445+0000] {subprocess.py:93} INFO -     875 # Convert BytesIO or file objects passed with an encoding
[2025-08-12T12:41:46.445+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:41:46.445+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gate\\Documents\\Jedha\\Projet\\4\\mlops-solar-flares\\data\\xrs_clean.parquet'
[2025-08-12T12:41:46.445+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:41:46.605+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T12:41:46.606+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T12:41:46.618+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T12:41:46.622+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=train_notebook, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T124135, end_date=20250812T124146
[2025-08-12T12:41:46.631+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 127 for task train_notebook (Bash command failed. The command returned a non-zero exit code 1.; 3265)
[2025-08-12T12:41:46.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T12:41:46.685+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T12:41:46.688+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
