[2025-08-12T14:09:13.012+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T14:09:13.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T14:09:13.079+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T14:09:13.080+0000] {taskinstance.py:2306} INFO - Starting attempt 16 of 18
[2025-08-12T14:09:13.096+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_notebook> on 2025-08-12 00:00:00+00:00
[2025-08-12T14:09:13.110+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6315) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T14:09:13.108+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'train_notebook', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmpgs4k0va9']
[2025-08-12T14:09:13.112+0000] {standard_task_runner.py:63} INFO - Started process 6316 to run task
[2025-08-12T14:09:13.112+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask train_notebook
[2025-08-12T14:09:13.185+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T14:09:13.300+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='train_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='16' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T14:09:13.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T14:09:13.316+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T14:09:13.320+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -euo pipefail\ntrap \'echo "[trap] SIGTERM -> arrêt propre"; exit 143\' TERM INT\ncd /opt/project/notebooks\n\n# Exécuter papermill vers un fichier temporaire et le supprimer\nOUT="$(mktemp -p /tmp ml_x_ray_sensor_run_XXXXXX.ipynb)"\npython -m papermill -k *** ml_x_ray_sensor.ipynb "$OUT"\necho "Notebook exécuté -> $OUT"\nrm -f "$OUT"']
[2025-08-12T14:09:13.349+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T14:09:15.419+0000] {subprocess.py:93} INFO - Input Notebook:  ml_x_ray_sensor.ipynb
[2025-08-12T14:09:15.420+0000] {subprocess.py:93} INFO - Output Notebook: /tmp/ml_x_ray_sensor_run_qm4YZt.ipynb
[2025-08-12T14:09:17.388+0000] {subprocess.py:93} INFO - Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: ***
[2025-08-12T14:10:27.663+0000] {subprocess.py:93} INFO - Executing:   5%|▌         | 1/20 [00:05<01:49,  5.79s/cell]Executing:  10%|█         | 2/20 [00:05<00:44,  2.45s/cell]Executing:  20%|██        | 4/20 [00:06<00:15,  1.04cell/s]Executing:  25%|██▌       | 5/20 [00:06<00:14,  1.05cell/s]Executing:  35%|███▌      | 7/20 [00:07<00:07,  1.67cell/s]Executing:  40%|████      | 8/20 [00:07<00:06,  1.87cell/s]Executing:  55%|█████▌    | 11/20 [00:08<00:02,  3.03cell/s]Executing:  65%|██████▌   | 13/20 [00:08<00:01,  4.18cell/s]Executing:  70%|███████   | 14/20 [01:10<01:12, 12.04s/cell]Executing:  75%|███████▌  | 15/20 [01:10<00:47,  9.49s/cell]Executing:  85%|████████▌ | 17/20 [01:10<00:17,  5.91s/cell]Executing:  90%|█████████ | 18/20 [01:12<00:08,  4.01s/cell]
[2025-08-12T14:10:27.679+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T14:10:27.680+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-08-12T14:10:27.680+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 88, in _run_code
[2025-08-12T14:10:27.680+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/__main__.py", line 4, in <module>
[2025-08-12T14:10:27.681+0000] {subprocess.py:93} INFO -     papermill()
[2025-08-12T14:10:27.681+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
[2025-08-12T14:10:27.682+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-08-12T14:10:27.682+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T14:10:27.682+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
[2025-08-12T14:10:27.683+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-08-12T14:10:27.683+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-08-12T14:10:27.684+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
[2025-08-12T14:10:27.684+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-08-12T14:10:27.685+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T14:10:27.685+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
[2025-08-12T14:10:27.685+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-08-12T14:10:27.686+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T14:10:27.686+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
[2025-08-12T14:10:27.686+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-08-12T14:10:27.687+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T14:10:27.687+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
[2025-08-12T14:10:27.688+0000] {subprocess.py:93} INFO -     execute_notebook(
[2025-08-12T14:10:27.688+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-08-12T14:10:27.688+0000] {subprocess.py:93} INFO -     raise_for_execution_errors(nb, output_path)
[2025-08-12T14:10:27.689+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-08-12T14:10:27.689+0000] {subprocess.py:93} INFO -     raise error
[2025-08-12T14:10:27.690+0000] {subprocess.py:93} INFO - papermill.exceptions.PapermillExecutionError:
[2025-08-12T14:10:27.690+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T14:10:27.690+0000] {subprocess.py:93} INFO - Exception encountered at "In [16]":
[2025-08-12T14:10:27.691+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T14:10:27.691+0000] {subprocess.py:93} INFO - ModuleNotFoundError                       Traceback (most recent call last)
[2025-08-12T14:10:27.692+0000] {subprocess.py:93} INFO - Cell In[16], line 20
[2025-08-12T14:10:27.692+0000] {subprocess.py:93} INFO -      18 # Evidently 0.7+
[2025-08-12T14:10:27.692+0000] {subprocess.py:93} INFO -      19 from evidently import Report
[2025-08-12T14:10:27.693+0000] {subprocess.py:93} INFO - ---> 20 from evidently.metric_preset import ClassificationPreset
[2025-08-12T14:10:27.693+0000] {subprocess.py:93} INFO -      21 from evidently.metrics.data_drift.data_definition import (
[2025-08-12T14:10:27.693+0000] {subprocess.py:93} INFO -      22     DataDefinition, MulticlassClassification
[2025-08-12T14:10:27.694+0000] {subprocess.py:93} INFO -      23 )
[2025-08-12T14:10:27.694+0000] {subprocess.py:93} INFO -      25 # MLflow tracking (ne pas toucher au docker)
[2025-08-12T14:10:27.694+0000] {subprocess.py:93} INFO - 
[2025-08-12T14:10:27.695+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'evidently.metric_preset'
[2025-08-12T14:10:27.695+0000] {subprocess.py:93} INFO - 
[2025-08-12T14:10:27.883+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T14:10:27.884+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T14:10:27.896+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T14:10:27.900+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=train_notebook, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T140913, end_date=20250812T141027
[2025-08-12T14:10:27.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 142 for task train_notebook (Bash command failed. The command returned a non-zero exit code 1.; 6316)
[2025-08-12T14:10:27.942+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T14:10:27.958+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T14:10:27.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
