[2025-08-12T13:56:57.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T13:56:57.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T13:56:57.886+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T13:56:57.887+0000] {taskinstance.py:2306} INFO - Starting attempt 13 of 15
[2025-08-12T13:56:57.904+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_notebook> on 2025-08-12 00:00:00+00:00
[2025-08-12T13:56:57.916+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'train_notebook', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmp150stf62']
[2025-08-12T13:56:57.919+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask train_notebook
[2025-08-12T13:56:57.920+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5817) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T13:56:57.921+0000] {standard_task_runner.py:63} INFO - Started process 5818 to run task
[2025-08-12T13:56:57.986+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T13:56:58.087+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='train_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T13:56:58.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T13:56:58.102+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T13:56:58.104+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -euo pipefail\ntrap \'echo "[trap] SIGTERM -> arrêt propre"; exit 143\' TERM INT\ncd /opt/project/notebooks\n\n# Exécuter papermill vers un fichier temporaire et le supprimer\nOUT="$(mktemp -p /tmp ml_x_ray_sensor_run_XXXXXX.ipynb)"\npython -m papermill -k *** ml_x_ray_sensor.ipynb "$OUT"\necho "Notebook exécuté -> $OUT"\nrm -f "$OUT"']
[2025-08-12T13:56:58.117+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T13:56:59.671+0000] {subprocess.py:93} INFO - Input Notebook:  ml_x_ray_sensor.ipynb
[2025-08-12T13:56:59.672+0000] {subprocess.py:93} INFO - Output Notebook: /tmp/ml_x_ray_sensor_run_C6fJ6z.ipynb
[2025-08-12T13:57:01.524+0000] {subprocess.py:93} INFO - Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: ***
[2025-08-12T13:57:07.465+0000] {subprocess.py:93} INFO - Executing:   5%|▌         | 1/20 [00:06<02:02,  6.43s/cell]Executing:   5%|▌         | 1/20 [00:07<02:27,  7.75s/cell]
[2025-08-12T13:57:07.476+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T13:57:07.477+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-08-12T13:57:07.477+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 88, in _run_code
[2025-08-12T13:57:07.478+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/__main__.py", line 4, in <module>
[2025-08-12T13:57:07.478+0000] {subprocess.py:93} INFO -     papermill()
[2025-08-12T13:57:07.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
[2025-08-12T13:57:07.479+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-08-12T13:57:07.479+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:57:07.480+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
[2025-08-12T13:57:07.480+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-08-12T13:57:07.481+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-08-12T13:57:07.481+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
[2025-08-12T13:57:07.482+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-08-12T13:57:07.482+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:57:07.483+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
[2025-08-12T13:57:07.483+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-08-12T13:57:07.484+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:57:07.485+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
[2025-08-12T13:57:07.485+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-08-12T13:57:07.486+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T13:57:07.486+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
[2025-08-12T13:57:07.487+0000] {subprocess.py:93} INFO -     execute_notebook(
[2025-08-12T13:57:07.487+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-08-12T13:57:07.488+0000] {subprocess.py:93} INFO -     raise_for_execution_errors(nb, output_path)
[2025-08-12T13:57:07.488+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-08-12T13:57:07.489+0000] {subprocess.py:93} INFO -     raise error
[2025-08-12T13:57:07.489+0000] {subprocess.py:93} INFO - papermill.exceptions.PapermillExecutionError:
[2025-08-12T13:57:07.490+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T13:57:07.490+0000] {subprocess.py:93} INFO - Exception encountered at "In [1]":
[2025-08-12T13:57:07.491+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T13:57:07.491+0000] {subprocess.py:93} INFO - ModuleNotFoundError                       Traceback (most recent call last)
[2025-08-12T13:57:07.492+0000] {subprocess.py:93} INFO - Cell In[1], line 31
[2025-08-12T13:57:07.492+0000] {subprocess.py:93} INFO -      29 from mlflow.models.signature import infer_signature
[2025-08-12T13:57:07.493+0000] {subprocess.py:93} INFO -      30 from evidently import Report, Dataset, DataDefinition, MulticlassClassification
[2025-08-12T13:57:07.493+0000] {subprocess.py:93} INFO - ---> 31 from evidently.metric_preset import ClassificationPreset
[2025-08-12T13:57:07.494+0000] {subprocess.py:93} INFO -      33 # ================== 0) Config ==================
[2025-08-12T13:57:07.494+0000] {subprocess.py:93} INFO -      35 from sklearn.metrics import (
[2025-08-12T13:57:07.495+0000] {subprocess.py:93} INFO -      36     accuracy_score, balanced_accuracy_score, f1_score,
[2025-08-12T13:57:07.495+0000] {subprocess.py:93} INFO -      37     confusion_matrix, classification_report
[2025-08-12T13:57:07.495+0000] {subprocess.py:93} INFO -      38 )
[2025-08-12T13:57:07.496+0000] {subprocess.py:93} INFO - 
[2025-08-12T13:57:07.496+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'evidently.metric_preset'
[2025-08-12T13:57:07.497+0000] {subprocess.py:93} INFO - 
[2025-08-12T13:57:07.732+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T13:57:07.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T13:57:07.749+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T13:57:07.754+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=train_notebook, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T135657, end_date=20250812T135707
[2025-08-12T13:57:07.776+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 139 for task train_notebook (Bash command failed. The command returned a non-zero exit code 1.; 5818)
[2025-08-12T13:57:07.819+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T13:57:07.838+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T13:57:07.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
