[2025-08-12T13:39:42.358+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T13:39:42.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T13:39:42.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T13:39:42.415+0000] {taskinstance.py:2306} INFO - Starting attempt 9 of 10
[2025-08-12T13:39:42.427+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_notebook> on 2025-08-12 00:00:00+00:00
[2025-08-12T13:39:42.435+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'train_notebook', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmp48a6e2zo']
[2025-08-12T13:39:42.438+0000] {standard_task_runner.py:91} INFO - Job 135: Subtask train_notebook
[2025-08-12T13:39:42.440+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5091) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T13:39:42.440+0000] {standard_task_runner.py:63} INFO - Started process 5092 to run task
[2025-08-12T13:39:42.488+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.train_notebook scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T13:39:42.563+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='train_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T13:39:42.564+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T13:39:42.582+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T13:39:42.586+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -e\nmkdir -p /opt/project/notebooks/runs\ncd /opt/project/notebooks\nOUT="ml_x_ray_sensor_run_20250812T000000.ipynb"\npython -m papermill -k *** ml_x_ray_sensor.ipynb "$OUT"\necho "Notebook exécuté -> $OUT"']
[2025-08-12T13:39:42.603+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T13:39:44.100+0000] {subprocess.py:93} INFO - Input Notebook:  ml_x_ray_sensor.ipynb
[2025-08-12T13:39:44.101+0000] {subprocess.py:93} INFO - Output Notebook: ml_x_ray_sensor_run_20250812T000000.ipynb
[2025-08-12T13:39:45.830+0000] {subprocess.py:93} INFO - Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: ***
[2025-08-12T13:40:14.538+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-08-12T13:40:14.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-12T13:40:14.546+0000] {process_utils.py:132} INFO - Sending 15 to group 5092. PIDs of all processes in the group: [5093, 5095, 5114, 5092]
[2025-08-12T13:40:14.548+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 5092
[2025-08-12T13:40:14.549+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-12T13:40:14.550+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-08-12T13:40:14.551+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T13:40:14.565+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-08-12T13:40:14.572+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=train_notebook, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T133942, end_date=20250812T134014
[2025-08-12T13:40:14.602+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5092, status='terminated', exitcode=2, started='13:39:41') (5092) terminated with exit code 2
[2025-08-12T13:40:14.605+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5095, status='terminated', started='13:39:42') (5095) terminated with exit code None
[2025-08-12T13:40:14.605+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5093, status='terminated', started='13:39:42') (5093) terminated with exit code None
[2025-08-12T13:40:15.351+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5114, status='terminated', started='13:39:44') (5114) terminated with exit code None
