[2025-08-12T16:21:45.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T16:21:45.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.run_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T16:21:45.536+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.run_notebook scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T16:21:45.546+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-12T16:21:45.569+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_notebook> on 2025-08-12 00:00:00+00:00
[2025-08-12T16:21:45.589+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8755) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T16:21:45.587+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'run_notebook', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmpfqs4nki_']
[2025-08-12T16:21:45.591+0000] {standard_task_runner.py:91} INFO - Job 150: Subtask run_notebook
[2025-08-12T16:21:45.591+0000] {standard_task_runner.py:63} INFO - Started process 8756 to run task
[2025-08-12T16:21:45.679+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.run_notebook scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T16:21:45.856+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T16:21:45.860+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T16:21:45.893+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T16:21:45.898+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -euo pipefail\ncd /opt/project/notebooks\nOUT="ml_x_ray_sensor_generated.ipynb"\nTMP="$(mktemp -p /tmp ml_x_tmp_XXXXXX.ipynb)"\npython -m papermill -k *** ml_x_ray_sensor.ipynb "$TMP"\nmv -f "$TMP" "$OUT"\necho "Notebook généré -> $OUT"']
[2025-08-12T16:21:45.925+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T16:21:48.077+0000] {subprocess.py:93} INFO - Input Notebook:  ml_x_ray_sensor.ipynb
[2025-08-12T16:21:48.078+0000] {subprocess.py:93} INFO - Output Notebook: /tmp/ml_x_tmp_Tpoeit.ipynb
[2025-08-12T16:21:50.288+0000] {subprocess.py:93} INFO - Executing:   0%|          | 0/27 [00:00<?, ?cell/s]Executing notebook with kernel: ***
[2025-08-12T16:23:05.878+0000] {subprocess.py:93} INFO - Executing:   4%|▎         | 1/27 [00:08<03:44,  8.62s/cell]Executing:   7%|▋         | 2/27 [00:08<01:33,  3.73s/cell]Executing:  11%|█         | 3/27 [00:09<00:50,  2.09s/cell]Executing:  19%|█▊        | 5/27 [00:10<00:30,  1.38s/cell]Executing:  26%|██▌       | 7/27 [00:11<00:18,  1.10cell/s]Executing:  30%|██▉       | 8/27 [00:11<00:14,  1.27cell/s]Executing:  33%|███▎      | 9/27 [00:11<00:11,  1.63cell/s]Executing:  41%|████      | 11/27 [00:12<00:07,  2.04cell/s]Executing:  48%|████▊     | 13/27 [00:12<00:04,  3.04cell/s]Executing:  52%|█████▏    | 14/27 [01:12<02:49, 13.01s/cell]Executing:  56%|█████▌    | 15/27 [01:12<02:00, 10.02s/cell]Executing:  63%|██████▎   | 17/27 [01:13<01:00,  6.05s/cell]Executing:  70%|███████   | 19/27 [01:13<00:32,  4.01s/cell]Executing:  74%|███████▍  | 20/27 [01:14<00:22,  3.22s/cell]Executing:  81%|████████▏ | 22/27 [01:15<00:11,  2.33s/cell]Executing:  89%|████████▉ | 24/27 [01:16<00:04,  1.65s/cell]Executing:  89%|████████▉ | 24/27 [01:17<00:09,  3.24s/cell]
[2025-08-12T16:23:05.895+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T16:23:05.896+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-08-12T16:23:05.896+0000] {subprocess.py:93} INFO -   File "<frozen runpy>", line 88, in _run_code
[2025-08-12T16:23:05.897+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/__main__.py", line 4, in <module>
[2025-08-12T16:23:05.897+0000] {subprocess.py:93} INFO -     papermill()
[2025-08-12T16:23:05.898+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
[2025-08-12T16:23:05.898+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-08-12T16:23:05.898+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:05.899+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
[2025-08-12T16:23:05.899+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-08-12T16:23:05.899+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-08-12T16:23:05.900+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
[2025-08-12T16:23:05.900+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-08-12T16:23:05.900+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:05.901+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
[2025-08-12T16:23:05.901+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-08-12T16:23:05.901+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:05.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
[2025-08-12T16:23:05.902+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-08-12T16:23:05.903+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:05.903+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
[2025-08-12T16:23:05.903+0000] {subprocess.py:93} INFO -     execute_notebook(
[2025-08-12T16:23:05.904+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-08-12T16:23:05.904+0000] {subprocess.py:93} INFO -     raise_for_execution_errors(nb, output_path)
[2025-08-12T16:23:05.904+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-08-12T16:23:05.905+0000] {subprocess.py:93} INFO -     raise error
[2025-08-12T16:23:05.905+0000] {subprocess.py:93} INFO - papermill.exceptions.PapermillExecutionError:
[2025-08-12T16:23:05.905+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T16:23:05.906+0000] {subprocess.py:93} INFO - Exception encountered at "In [20]":
[2025-08-12T16:23:05.906+0000] {subprocess.py:93} INFO - ---------------------------------------------------------------------------
[2025-08-12T16:23:05.907+0000] {subprocess.py:93} INFO - NameError                                 Traceback (most recent call last)
[2025-08-12T16:23:05.907+0000] {subprocess.py:93} INFO - Cell In[20], line 13
[2025-08-12T16:23:05.908+0000] {subprocess.py:93} INFO -      10 run_name = f"GBM_X_focus_threshold_{time.strftime('%Y%m%d-%H%M%S')}"
[2025-08-12T16:23:05.908+0000] {subprocess.py:93} INFO -      11 with mlflow.start_run(run_name=run_name) as run:
[2025-08-12T16:23:05.908+0000] {subprocess.py:93} INFO -      12     # -------- params / métriques / contexte --------
[2025-08-12T16:23:05.909+0000] {subprocess.py:93} INFO - ---> 13     mlflow.log_params(params)
[2025-08-12T16:23:05.909+0000] {subprocess.py:93} INFO -      14     mlflow.log_metrics(metrics)
[2025-08-12T16:23:05.909+0000] {subprocess.py:93} INFO -      15     mlflow.log_dict(context, "context.json")
[2025-08-12T16:23:05.910+0000] {subprocess.py:93} INFO - 
[2025-08-12T16:23:05.910+0000] {subprocess.py:93} INFO - NameError: name 'params' is not defined
[2025-08-12T16:23:05.911+0000] {subprocess.py:93} INFO - 
[2025-08-12T16:23:06.137+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T16:23:06.139+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T16:23:06.155+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T16:23:06.162+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_flares_train_12h, task_id=run_notebook, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T162145, end_date=20250812T162306
[2025-08-12T16:23:06.177+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 150 for task run_notebook (Bash command failed. The command returned a non-zero exit code 1.; 8756)
[2025-08-12T16:23:06.205+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T16:23:06.238+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T16:23:06.241+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
